import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { name: "Dashboard", path: "/dashboard" },
  { name: "Inbound", path: "/inbound" },
  { name: "Outbound", path: "/outbound" },
  { name: "Inventory", path: "/inventory" },
  { name: "Config", path: "/config" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <nav className="bg-gray-800 text-white p-4 flex gap-6">
            {navItems.map((item) => (
              <Link key={item.path} href={item.path} className="hover:underline">
                {item.name}
              </Link>
            ))}
          </nav>
          <main className="flex-1 p-8 bg-gray-50">{children}</main>
        </div>
      </body>
    </html>
  );
}
